apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.namespace }}-kafka-receiver-config
  namespace: {{ .Values.namespace | default "default" }}
data:
  # Add your configuration key-value pairs here
  KAFKA_BOOTSTRAP_SERVERS: {{ .Values.kafka.bootstrapServers }}
  KAFKA_TOPIC: {{ .Values.kafka.topic }}
  # Add more configuration as needed
