apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-kafka
  namespace: {{ .Values.namespace | default "default" }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: {{ .Values.kafka.image }}
        ports:
        - containerPort: {{ .Values.kafka.port }}
        env:
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: {{ .Release.Name }}-kafka
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: {{ .Release.Name }}-zookeeper:{{ .Values.zookeeper.port }}
        - name: KAFKA_CREATE_TOPICS
          value: {{ .Values.kafka.topics }}
