---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-zookeeper
spec:
  selector:
    app: zookeeper
  ports:
    - port: {{ .Values.zookeeper.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-kafka
spec:
  selector:
    app: kafka
  ports:
    - port: {{ .Values.kafka.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mongodb
spec:
  selector:
    app: mongodb
  ports:
    - port: {{ .Values.mongodb.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-kafka-sender
spec:
  selector:
    app: kafka-sender
  ports:
    - port: {{ .Values.kafkaSender.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-kafka-receiver
spec:
  selector:
    app: kafka-receiver
  ports:
    - port: {{ .Values.kafkaReceiver.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-frontend
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - port: {{ .Values.frontend.servicePort }}
      targetPort: {{ .Values.frontend.port }}
