zookeeper:
  image: wurstmeister/zookeeper
  port: 2181

kafka:
  image: wurstmeister/kafka
  port: 9092
  topics: "messages:1:1"

mongodb:
  image: mongo:latest
  port: 27017

kafkaSender:
  image: hw2_1-kafka-sender:latest
  port: 5000

kafkaReceiver:
  image: hw2_1-kafka-receiver:latest
  port: 6000

frontend:
  image: hw2_1-frontend:latest
  port: 80
  servicePort: 8000

namespace: default